# Generated by Django 5.1.1 on 2024-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tbl_category_tbl_register_tbl_slider_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('product_id', models.IntegerField()),
                ('product_image', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('pw', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_image', models.CharField(max_length=200, null=True)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('pw', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('order_date', models.DateField(null=True)),
            ],
        ),
    ]
