# Generated by Django 5.1.1 on 2024-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
