# Generated by Django 5.1.1 on 2024-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_tbl_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
